name: Playwright Docker Tests
on:
    push:
      branches: [ main, master ]
    pull_request:
      branches: [ main, master ]
    # Trigger nightly at 8:00 UTC (equivalent to 1 AM Pacific time)
    schedule:
      - cron: '0 8 * * *'     
jobs:
  test:
    timeout-minutes: 40
    runs-on: ubuntu-latest
    steps:
    - name: Checkout       
      uses: actions/checkout@v4      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Verify Docker Compose (optional, for debugging)
      run: |
        docker --version
        docker compose version # Verify that 'docker compose' (v2) is available
    - name: Show local time (for reference)
      run: |
         echo "Current time in UTC: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
         echo "Current time in PDT: $(TZ='America/Los_Angeles' date '+%Y-%m-%d %H:%M:%S PDT')"
    - name: Determine Playwright Project Name
      id: set_project_name
      run: |
        # 1. Check the event name
        if [[ "${{ github.event_name }}" == "schedule" ]]; then
          echo "PROJECT_NAME=" >> $GITHUB_ENV
          echo "Running all projects for nightly schedule running event" 
        else 
          echo "PROJECT_NAME=--project=chromium" >> $GITHUB_ENV 
          echo "Running with only chromium project"
        fi       
    - name: Build and run Docker Compose
      run: |
        docker compose up --build --abort-on-container-exit 
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 15